### ISSUE TITLE
Insecure site warning

### ISSUE THREAD

**Issue by brashrebel** [realbig/RBMC_TH_KNICHE#1]
Client contacted me to say they were contacted by someone who is getting a warning in their browser about this site having a higher likelihood of being malicious or something like that. The user was searching in Google in Safari and clicked on the home page link.

Might be related to this but I'm still looking:
![screenshot 2015-03-14 12 01 11](https://cloud.githubusercontent.com/assets/4993131/6652360/203da21c-ca42-11e4-9c86-c250d3eadd57.png)
Note the "free images" text in the meta description.

**Comment by brashrebel** [comment]
It appears this is the alt text for the giant background image.

**Comment by BigActual** [comment]
Were you able to change the alt text to something relevant?
Probable doesn't matter here with the new site going live.

**Comment by joelworsham** [comment]
Looks like it's fixed
