### ISSUE TITLE
Change Testimonials section title to something else. 

### ISSUE THREAD

**Issue by BigActual** [realbig/RBMC_TH_KNICHE#18]
Susan will send an email with a new title for the section.

**Comment by joelworsham** [comment]
Let me know when you get it.

**Comment by BigActual** [comment]
Reviews

**Comment by joelworsham** [comment]
Ah, you meant in the widget. For future reference, you can change the widget title.

**Comment by BigActual** [comment]
Yes, but also on the back-end, the CPT Title so the client isn't confused later.
