### ISSUE TITLE
Non standard right margin

### ISSUE THREAD

**Issue by BigActual** [realbig/RBMC_TH_KNICHE#2]
Symptom showing on http://kidniche-com.realbig.staging.wpengine.com/about/ where the right margin for each picture is different. Susan requested that they all be the same. The first image of the bird house (I think it's a bird house) is correct.

**Comment by BigActual** [comment]
Same issue is evident here: http://kidniche-com.realbig.staging.wpengine.com/lessons/

**Comment by joelworsham** [comment]
The reason for this is because the image was placed in the H2 tag. The margin is based on the font size. I'd recommend not placing images in H tags, but I can always change the margin to be a set px width, if you like.

**Comment by BigActual** [comment]
That has to be one of the WYSIWIG editor glitches where she placed it and then used the MCE dropdown to edit adjacent text styling. Not knowing that this text adjustment will cause a margin issue. Let's standardize all picture margins so that regardless of text styling there is not a change to image placement or image margin.

**Comment by joelworsham** [comment]
Sure

**Comment by BigActual** [comment]
How do we reopen this issue? On this page: http://kidniche-com.realbig.staging.wpengine.com/lessons/     The image margin on the right is not correct after you made changes. It's the featured image being brought to the archive page.

**Comment by BigActual** [comment]
Margin issue has reoccurred on the home page.
