### ISSUE TITLE
Flip Book plugin

### ISSUE THREAD

**Issue by BigActual** [realbig/RBMC_TH_KNICHE#22]
Steve will add it.

**Comment by joelworsham** [comment]
Why did you remove your assignment?

**Comment by BigActual** [comment]
Hmmm, I assigned all of the items I created for myself to myself. May have
been a mistake.

**Comment by joelworsham** [comment]
Trying to get out of work eh?

**Comment by BigActual** [comment]
I've added it, but there are, of course, some problems. Would you please take a look at the error messages coming up on the booklet settings page: http://kidniche-com.realbig.staging.wpengine.com/wp-admin/edit.php?post_type=wp-booklet2&page=wp-booklet2-settings

**Comment by joelworsham** [comment]
https://wordpress.org/support/topic/can-your-server-convert-pdf-filesno-please-contact-your-server-administrator?replies=1#post-7134102

**Comment by BigActual** [comment]
I see from the vendor's snappy response that this plugin is really important to them :(
Feel free to use an alternative. I'm not married to this. the client wants to display the first few pages of each book as a sample. She doesn't care what brand of flip book we use. I don't either.

**Comment by BigActual** [comment]
Any word on this?

**Comment by joelworsham** [comment]
Yes, developer responded. Contacting WP Engine now with the update.

**Comment by joelworsham** [comment]
The plugin is not supported by WP Engine. Will need to find alternative.

**Comment by BigActual** [comment]
OK, I'll let the client know you're working on an alternative.

**Comment by joelworsham** [comment]
Added a plugin that seems to be working.

http://kidniche-com.realbig.staging.wpengine.com/?publications=test

Add them under "Publications"

**Comment by BigActual** [comment]
Can we restyle the output? http://kidniche-com.realbig.staging.wpengine.com/books/whole-self-picture-prayer-book-biblical-learning-guide/

**Comment by BigActual** [comment]
Have the text wrap. Remove the large icon underneath.

**Comment by BigActual** [comment]
Can't find an x to close the pdf

**Comment by joelworsham** [comment]
It loads it in a new page

**Comment by BigActual** [comment]
Not for me.

**Comment by BigActual** [comment]
Pop up would be desired by the client.

**Comment by BigActual** [comment]
Double checked, it is opening in the same window.

**Comment by joelworsham** [comment]
Yes same window, but different page.

This plugin doesn't come with a pop-up. I think we're going to pretty limited here for finding a free plugin that works.

**Comment by BigActual** [comment]
Can you style the output?

**Comment by BigActual** [comment]
OK. Spoke with Susan. She's happy with the gallery. This issue may be closed.
