### ISSUE TITLE
Move Sub Titles to their appropriate field.

### ISSUE THREAD

**Issue by BigActual** [realbig/RBMC_TH_KNICHE#25]
When Joel completes adding a Sub Title field to the Books and to the Products, I'll move the copy around.

**Comment by joelworsham** [comment]
Let me know what you think

**Comment by BigActual** [comment]
Should look like this on product single:
![image](https://cloud.githubusercontent.com/assets/8271108/8499331/cc0337d2-215f-11e5-9f9a-4bf70427e59f.png)

**Comment by BigActual** [comment]
Should look like this on product single:
![image](https://cloud.githubusercontent.com/assets/8271108/8499382/26a39eb6-2160-11e5-859d-40eaec312704.png)

**Comment by BigActual** [comment]
Also the subtitles require a hyper link on the home page "Featured Item" listing and on the Books archive page.
