### ISSUE TITLE
Logo size unification

### ISSUE THREAD

**Issue by BigActual** [realbig/RBMC_TH_KNICHE#26]
Please modify the home page logo to match the logo size and placement found everywhere else on the site. (Where's my frowny face emoticon)

**Comment by BigActual** [comment]
Usen new logo for all: 
![kid-niche-logo-final](https://cloud.githubusercontent.com/assets/8271108/8458191/9dcbc7b2-1fe3-11e5-9d93-3a78489d558b.png)

**Comment by joelworsham** [comment]
Wait, you want the home page logo to NOT be bigger than other pages now?

**Comment by BigActual** [comment]
don't point your finger at me....

**Comment by BigActual** [comment]
...and yes, she's received enough feedback from a lot of people telling her it looks bad.

**Comment by joelworsham** [comment]
Just double checking

**Comment by BigActual** [comment]
Let's move that up half the height available between the current position and the top of the page, globally. I believe it was that hi on every other page before the change, Regardless, it seems low.
