### ISSUE TITLE
Privacy & Terms hidden.

### ISSUE THREAD

**Issue by BigActual** [realbig/RBMC_TH_KNICHE#29]
Privacy and Terms is hidden behind the captcha on the contact page. Please move down.

**Comment by joelworsham** [comment]
That's a bug outside the theme.

WHat about adding this plugin? It's a much nicer, modern re-captcha anyways.

https://wordpress.org/plugins/gravity-forms-no-captcha-recaptcha/

**Comment by joelworsham** [comment]
That's a bug outside the theme.

WHat about adding this plugin? It's a much nicer, modern re-captcha anyways.

https://wordpress.org/plugins/gravity-forms-no-captcha-recaptcha/

**Comment by BigActual** [comment]
Really doesn't matter to me how it's solved.

**Comment by joelworsham** [comment]
k

**Comment by joelworsham** [comment]
https://www.dropbox.com/s/yps3lrfqtpzb5b2/Screenshot%202015-07-02%2010.21.55.png?dl=0
