### ISSUE TITLE
Top Nav is responding/wrapping unnecessarily at around 750px 

### ISSUE THREAD

**Issue by BigActual** [realbig/RBMC_TH_KNICHE#3]
The top nav has three items and is pushing down the items to the right as the screen size goes through 750px, give or take.

**Comment by joelworsham** [comment]
#5 should fix this

**Comment by BigActual** [comment]
Almost. This may be a separate issue, but now the text that reads, "Howdy {First]" and Gravatar in the upper right corner of the horizontal, admin nav bar, is dropping onto the shopping cart area from 979 to 1200px.

**Comment by joelworsham** [comment]
Is it important for site admins to avoid this issue?

**Comment by joelworsham** [comment]
I typically don't do any styling to the WP admin bar.
