### ISSUE TITLE
Add home icon to the left of the About link in the main nav. bar.

### ISSUE THREAD

**Issue by BigActual** [realbig/RBMC_TH_KNICHE#30]

**Comment by joelworsham** [comment]
I will need to make adjustments to fit it. Either make the logo smaller or make the font-size smaller

**Comment by joelworsham** [comment]
Should this icon link to the home page? (I'm assuming yes)

**Comment by BigActual** [comment]
Yes and see the other issues. There is one to make the logo on the home page smaller, matching the global look elsewhere on the site.
