### ISSUE TITLE
Logo cut off in bottom right corner.

### ISSUE THREAD

**Issue by BigActual** [realbig/RBMC_TH_KNICHE#31]
Please adjust. Maybe z index??

**Comment by joelworsham** [comment]
Where? I don't see this.

**Comment by BigActual** [comment]
![image](https://cloud.githubusercontent.com/assets/8271108/8620192/f8d9299c-26eb-11e5-98b4-3f028363bb1f.png)

**Comment by BigActual** [comment]
the bottom of the tree is cut off.

**Comment by BigActual** [comment]
Maybe 5 pixels or so

**Comment by joelworsham** [comment]
That's just how the image I have is. Maybe I'm not using the most recent image?

**Comment by BigActual** [comment]
Let me upload the most recent here for you.

**Comment by BigActual** [comment]
![kid-niche-logo-final](https://cloud.githubusercontent.com/assets/8271108/8620385/4fe3ec58-26ed-11e5-876f-c4e6692985a8.png)
