### ISSUE TITLE
Client is confused. Fields in control panel for home page contact information do not control footer contact information.

### ISSUE THREAD

**Issue by BigActual** [realbig/RBMC_TH_KNICHE#33]
Could you make it so that the footer is not controlled from the widget screen, but by the home page fields?

**Comment by joelworsham** [comment]
Where are you seeing these fields?

**Comment by joelworsham** [comment]
Oh I see. Those fields shouldn't be there.

**Comment by joelworsham** [comment]
I've remove them.

**Comment by BigActual** [comment]
Well, I was hoping for the other way around, but OK.

**Comment by joelworsham** [comment]
They weren't in use anywhere else. It could be possible to implement them as settings somewhere else, but it doesn't seem necessary for this site.

**Comment by BigActual** [comment]
It's fine. Really. It's looking great.
