### ISSUE TITLE
Book Single, center align Featured Image in it's column

### ISSUE THREAD

**Issue by BigActual** [realbig/RBMC_TH_KNICHE#35]
Center alight the featured image in the first column, left to right please.

**Comment by joelworsham** [comment]
It is center aligned. I don't understand what you're asking

**Comment by BigActual** [comment]
![image](https://cloud.githubusercontent.com/assets/8271108/8620112/6c6bb2b8-26eb-11e5-8178-ec2fbb31f1de.png)
The image should sit centered on the second line and the text should work within the third and sixth line.

**Comment by joelworsham** [comment]
Right, it's fixed now (just not pushed yet)
