### ISSUE TITLE
Template Issue in newly added book

### ISSUE THREAD

**Issue by BigActual** [realbig/RBMC_TH_KNICHE#37]
This book is not displaying the correct imagery at the top for a book.

http://kidniche-com.realbig.staging.wpengine.com/books/whole-self-picture-prayer-book-biblical-learning-guide/

**Comment by joelworsham** [comment]
That's because there's no snippet entered. Do you want to be able to show the picture without a snippet?

**Comment by BigActual** [comment]
Added description.
