### ISSUE TITLE
Kid Niche Logo Responding like a rock star (With too much drama LOL)

### ISSUE THREAD

**Issue by BigActual** [realbig/RBMC_TH_KNICHE#4]
As the screen becomes narrower, and starting at about 750 px the logo starts to drop away from it's appointed position. As the screen becomes narrower, it drops further. On my 1080p monitor, it can drop all the way off the screen. The logo should stay at the top.

**Comment by joelworsham** [comment]
The logo is currently "fixed" from the bottom. I can change this to the top instead.

**Comment by BigActual** [comment]
Perfect. Thanks.
