### ISSUE TITLE
Books Archive most recent entry displaying info from the book most previously entered before.

### ISSUE THREAD

**Issue by BigActual** [realbig/RBMC_TH_KNICHE#41]
If you click the title it goes to the newest book, but for some reason, the title, image and snippet are coming from the one we entered last week. Weird.

**Comment by BigActual** [comment]
![image](https://cloud.githubusercontent.com/assets/8271108/8620907/a45ec214-26f0-11e5-925c-d4aab11a7fe6.png)

**Comment by joelworsham** [comment]
Urgh

**Comment by BigActual** [comment]
![image](https://cloud.githubusercontent.com/assets/8271108/8620953/e664f232-26f0-11e5-800c-ae5405726777.png)

**Comment by joelworsham** [comment]
_like_

**Comment by joelworsham** [comment]
It's because they are both linked to the same product.

**Comment by joelworsham** [comment]
Which I'm noticing it's near impossible to tell what product is what in that dropdown because so many have the same title...

**Comment by joelworsham** [comment]
How could I help you with this? Including the subtitle in the dropdown options?

**Comment by BigActual** [comment]
It's super frustrating. yes can you do that?
