### ISSUE TITLE
Home banner link

### ISSUE THREAD

**Issue by joelworsham** [realbig/RBMC_TH_KNICHE#43]
Link to custom URL if clicked

**Comment by BigActual** [comment]
??

**Comment by joelworsham** [comment]
What?

**Comment by BigActual** [comment]
Sorry for my shorthand, I was wondering which item this addresses?

**Comment by joelworsham** [comment]
"1) Home Page -- Please adjust book image on top green banner so that the whole so that it is centered in the current background. This should reveal the whole bottom of the trunk which has been cut off just a bit.​ Complete I like the size of the green banner. The book is still too small in that space. Also, on a phone screen, the green background is in two different color sections--one with green diamonds and one solid green. Please advise.

Is it also possible to link to a description of the book, if the image of the book is clicked on? "
