### ISSUE TITLE
Featured video on home page above lessons

### ISSUE THREAD

**Issue by joelworsham** [realbig/RBMC_TH_KNICHE#51]

**Comment by joelworsham** [comment]
https://www.youtube.com/watch?v=JXlFhiysg2s

**Comment by BigActual** [comment]
I don't see this. Is it still to be uploaded to the server?

**Comment by joelworsham** [comment]
Sorry, forgot to actually set the video in the home page settings. It's accessible by you and Susan via "Edit Page", on the home page. (I've set it for now)
