### ISSUE TITLE
Remove padding around image in the Banner on the home page. All four sides.

### ISSUE THREAD

**Issue by BigActual** [realbig/RBMC_TH_KNICHE#58]
![untitled-1](https://cloud.githubusercontent.com/assets/8271108/8673914/7542ec60-2a08-11e5-8182-fab17b644c31.jpg)

**Comment by joelworsham** [comment]
I would probably advise against it, but I'm open to it. Why do you want it removed?

**Comment by BigActual** [comment]
The image has to go to the edge.  See how the shadow is cut off. I'm asking for all margins/padding to be removed so that the image sits centered in the column. Client will control the image placement. We discussed it and she's aware of how to control it.
