### ISSUE TITLE
Testimonials rotating very quickly

### ISSUE THREAD

**Issue by BigActual** [realbig/RBMC_TH_KNICHE#6]
Could the change occur at 6.5 seconds? I may change it again. Do you want to add a control area to leave development alone? I don't mind either way.

**Comment by joelworsham** [comment]
Yeah I'll add a simple box to enter delay in seconds.

**Comment by BigActual** [comment]
> Will this control be in the Kid Niche Settings area of the dashboard?

**Comment by joelworsham** [comment]
Yeah, I'll put it there
