### ISSUE TITLE
YouTube embed programming change since site launch

### ISSUE THREAD

**Issue by BigActual** [realbig/RBMC_TH_KNICHE#60]
As described by the client; videos, when embedded from YouTube, used to automatically have the coding added to remove recommended YouTube videos. Now, it doesn't do that. I see that videos untouched by Susan since the launch still present correctly when the video is finished. Anything she's touched presents the user with options to watch more videos. Here's a screenshot of a video that presents correctly:
![image](https://cloud.githubusercontent.com/assets/8271108/8758479/a4c17af4-2cb2-11e5-8ded-eeaa0fd85c35.png)
Here's one that's not:
![image](https://cloud.githubusercontent.com/assets/8271108/8758504/cbb2a656-2cb2-11e5-85f6-9ee75be6c6e1.png)

Based on client input, we were able to provide coding that made it possible for her to use the YouTube share functionality, without adding the rel=0 on her own. Please advise.

**Comment by joelworsham** [comment]
I've added `rel=0` to the link. This can be done from the edit home page screen.

https://www.dropbox.com/s/okh3v856lydc65s/Screenshot%202015-07-21%2008.55.01.png?dl=0

**Comment by joelworsham** [comment]
Well, actually it seems that adding that did not work

**Comment by BigActual** [comment]
Kyle added a script that added the rel=0 automagically for the customer.

**Comment by joelworsham** [comment]
Well, even so it doesn't seem to be working for this video. Probably the way it's embedded, but I'll look into it.

**Comment by BigActual** [comment]
At least that's what was described to me.

**Comment by BigActual** [comment]
KK

**Comment by joelworsham** [comment]
I don't see anything in the old theme that would do that, and I don't think we've removed any plugins.

@brashrebel Insight?

Also, I pushed some code that fixes this on the home page.

**Comment by brashrebel** [comment]
When the client asked for this ages ago, I looked into doing it manually and told the client to append the whatever to the links but it wouldn't work. I then activated some random plugin and it worked so I said never mind, we're good. At least I think that is what happened.

**Comment by brashrebel** [comment]
Just activated the stupid plugin. Sheesh.

**Comment by joelworsham** [comment]
Good job
