### ISSUE TITLE
Numbering is off on Activities pages

### ISSUE THREAD

**Issue by BigActual** [realbig/RBMC_TH_KNICHE#61]
Numbering should be 1a - 10c, 11a - 20c, etc. 30 activities per page. Please advise.

**Comment by joelworsham** [comment]
Ah okay, I was under the impression it was 10 total per page for some reason

**Comment by brashrebel** [comment]
Client is pissed about the delay in delivering this. Is there any way that I can take care of it? Please point me in the right direction.

**Comment by joelworsham** [comment]
It may take just as long to explain it as to actually just doing it. But you're more than welcome to analyze the code.
