### ISSUE TITLE
Move company and tax ID fields

### ISSUE THREAD

**Issue by brashrebel** [realbig/RBMC_TH_KNICHE#68]
The second item in the client's request.

**Comment by d4mation** [comment]
At User Creation, should we confirm that no one else is using the same Tax ID? Or should we allow multiple Users to have the same one? (In the event that perhaps one company has multiple User accounts for whatever reason).

**Comment by d4mation** [comment]
Also, fields have been moved.

**Comment by brashrebel** [comment]
Good thought. I think for now we'll leave it but that might make a nice enhancement later. Thanks.
