### ISSUE TITLE
WP Admin Nav bar disappearing

### ISSUE THREAD

**Issue by BigActual** [realbig/RBMC_TH_KNICHE#7]
Admin top navigation bar for WordPress is not present on
http://kidniche-com.realbig.staging.wpengine.com/books/

**Comment by joelworsham** [comment]
This was due to a PHP error. The entire footer was not being loaded, which is where the admin bar is loaded.

It appears as though this problem does not still exist. Does it still exist for you?

**Comment by BigActual** [comment]
The problem does not exist. Thanks
