### ISSUE TITLE
Adjust message about shipping discount on wholesale pages

### ISSUE THREAD

**Issue by brashrebel** [realbig/RBMC_TH_KNICHE#70]
Should read "Free Shipping & Handling on $50 Orders — Mix & Match." instead.

**Comment by d4mation** [comment]
Found it while trying to get something else working.

**Comment by d4mation** [comment]
Moved this to `woocommerce/overrrides.php` hooking into `woocommerce_check_cart_items` as it was showing for users that weren't Wholesale Customers. I figured that would be very confusing to regular Customers when they weren't getting free shipping on orders over $50.
