### ISSUE TITLE
Implement wholesale discounted pricing

### ISSUE THREAD

**Issue by brashrebel** [realbig/RBMC_TH_KNICHE#72]
I have no idea how much of this has been done or if any such feature already exists. We need to make sure that users who signup with the wholesale signup form are automatically given different pricing as follows:

```
Prayer Cards                                                                      
$5.00 Retail / Wholesale $2.75

MWSBY – The Prayer Guide (Frog)                          
$11.50 Retail / Wholesale $6.33

Pray Often Pray Real – The Prayer Journal            
$13.50 Retail / Wholesale $7.43

MWSBY – The Yellow Book                                          
$14.95 Retail / Wholesale $8.22

MWSBY – Large Yellow Book (Spiral)                      
$35.00 Retail / Wholesale $19.25

MWSBY – The Green Book                                          
$18.95 Retail / Wholesale $10.42

MWSBY – The Study Guide                                          
$25.00 Retail / Wholesale $13.75
```

It doesn't appear that the current signup form registers them as users. I think that is what has to happen. We will likely need to modify that form to also register them as a user with a custom role which will need to be created. A separate plugin is ideal but it could make our lives easier to just use the functions file. Open to discussion.

This issue is getting big. To summarize, a custom role "wholesaler" needs to exist. Users with that role get the discounted pricing. The form should register them. Probably trigger an activation/set your password email or something.

**Comment by brashrebel** [comment]
Also, there are shipping rates for regular retail that should not apply for wholesale buyers. They get the deal described in #70.

**Comment by d4mation** [comment]
Base prices for Wholesale Customers have been added.

While testing this I noticed some quirks in the Wholesale User creation Process in how it sends Users an email. I'm going to fix that after I get the Shipping rates in.
