### ISSUE TITLE
Existing user working through process of becoming a Wholesale User

### ISSUE THREAD

**Issue by BigActual** [realbig/RBMC_TH_KNICHE#78]
As noted in #77 An existing user can not complete the Wholesale form. Let's apply some logic to check if the current user is registered and then repurposte their existing profile?

**Comment by d4mation** [comment]
Currently the Form is only able to support User Creation, but I could make a separate form for Updating the User to become a `wholesale_customer` and show that one instead based on whether the User is logged in or not. We would just have to be sure not to fill one out while logged in as an Administrator, as it would remove our Administrator status.

**Comment by BigActual** [comment]
Perfectly logical. Go.

**Comment by d4mation** [comment]
The New Form is largely the same, the primary difference being that it doesn't ask for a User Name.

It pre-populates the Email, Name, Company, and Address Fields based on any already assigned to the User if they exist (From being a regular Customer, for example). This gives them a convenient opportunity to update this information if they'd like.

The Confirmation Message tells the User that all they need to do is "Reload the page", which is all it takes. Then any Prompts about becoming a Wholesale Customer disappear and the new prices and shipping methods apply.

**Comment by BigActual** [comment]
Thanks.
