### ISSUE TITLE
Add additional snippet for site verification

### ISSUE THREAD

**Issue by BigActual** [realbig/RBMC_TH_KNICHE#79]
Do not replace the existing snippet. These are for separate items. Please add to the `<head>` right before the first `<body>` section.

**Comment by BigActual** [comment]
<meta name="google-site-verification" content="XD-sLL0wtQneZCDoVZKeN14rXMjTJjTpo0F5_169psY" />

**Comment by BigActual** [comment]
'<meta name="google-site-verification" content="XD-sLL0wtQneZCDoVZKeN14rXMjTJjTpo0F5_169psY" />'

**Comment by BigActual** [comment]
```
<meta name="google-site-verification" content="XD-sLL0wtQneZCDoVZKeN14rXMjTJjTpo0F5_169psY" />
```

**Comment by BigActual** [comment]
```
<meta name="msvalidate.01" content="BC0CA43152825FE3AF36AECF5EC2E1D0" />
```

**Comment by d4mation** [comment]
Looks like I added one of them twice as I had gotten it from Kyle a couple days ago. Didn't realize they were the same. I'll fix that.

**Comment by BigActual** [comment]
Probalby not. This one's for www.kidniche.com, which is separate from kidniche.com in the eyes of google. In the end there should be four. two for google and two for bing. It just takes me time to register each one and then get the code.

**Comment by d4mation** [comment]
Nah, the one I removed was truly identical. I double checked just now from my Slack logs. It was exactly the same as the first Meta Tag in this Issue.

**Comment by BigActual** [comment]
Google Dashboard used to generate a separate code for both versions and I didn't look at it to see. I just verified the site at my end and it's working fine so... That's awesome. Fewer times I have to bug you guys. thanks
