### ISSUE TITLE
Update code for Universal Event Tracking

### ISSUE THREAD

**Issue by BigActual** [realbig/RBMC_TH_KNICHE#80]
This is the updated Universal Analytics tracking code for kidniche.com. It adds the functionality for enhanced link attribution. To get all the benefits of Universal Analytics for this property, I need to make sure that this presents universally on every page, post, product, checkout workflow, thank you pages, etc. 

```
<script>
```

  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-71404004-1', 'auto');
  ga('require', 'linkid');
  ga('send', 'pageview');

</script>

**Comment by BigActual** [comment]
I'll Slack you the code as well Kyle.

**Comment by d4mation** [comment]
I added it to the Footer in this case because the Plugin for it on the Multi-Site doesn't support `ga('require', 'linkid');` and would have instead only done `ga('send', 'pageview');`
