### ISSUE TITLE
Some WooCommerce bugs just popped up

### ISSUE THREAD

**Issue by brashrebel** [realbig/RBMC_TH_KNICHE#81]
This may relate to a recent WC update or something but the following issues recently arose:

--Buy buttons disappeared.
--Retail prices and sale prices disappeared.
--Sale emblems disappeared.
--No "edit page" option in the top black administrator menu for the Shop Page.
--No regular price and sale price fields for the product called Pray Often Pray Real, The Pray-Like-Jesus Journal. The shop page currently shows its price as Free!

**Comment by d4mation** [comment]
I am pretty sure I have this figured out.

Somehow the values for the Role Based Prices Plugin got wiped and the Plugin doesn't seem to have any type of fallback/error message to help you determine what's happening.

When I deactivated the plugin, all the prices, buttons, sale emblems, etc. re-appeared. 

When I re-activated it and manually set a price to show on a product for Administrator-level Users, everything showed again for that Product.

**Comment by d4mation** [comment]
I've sorted this out by ensuring that the following User Roles were set to show the regular price:
- Administrator
- Customer
- Shop Manager
- Logged Out/Visitor

I'm not sure what had changed between when we set it up and now, as it used to default to the Price set within WooCommerce itself if there was no Role-Specific Price set.

I'm going to try to make a backup of those settings just-in-case.
